name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Show Xcode version
        run: xcodebuild -version
        
      - name: Show available simulators
        run: xcrun simctl list devices available
      
      - name: Install Ruby dependencies
        run: bundle install
      
      - name: Run tests
        run: bundle exec fastlane ios test
        
      - name: Test secrets in Fastlane
        run: bundle exec fastlane ios check_ci_secrets
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
